import styled from "styled-components";
import DateComponent from "./DateComponent";
import Links from "./LinkComponent";

const Gist = ({ gist }) => {
  return (
    <GistWrapper>
      <div style={{ display: "flex", justifyContent: "space-between" }}>
        <div style={{ display: "flex", alignItems: "center", gap: 5 }}>
          <img
            src={gist.owner.avatar_url}
            alt="Avatar"
            width={30}
            style={{ borderRadius: "50%" }}
          />
          <span>
            <a href={gist.owner.html_url} target="_blank" rel="noreferrer">
              {gist.owner.login}
            </a>
          </span>
        </div>
        <div style={{ display: "flex", gap: 15 }}>
          <Links
            linkType={"file"}
            linkName="file"
            link={gist.html_url}
            files={gist.files}
          />
          <Links
            linkType={"fork"}
            linkName="Forks"
            link={gist.forks_url}
            files={gist.files}
          />
          <Links
            linkType={"comments"}
            linkName="comments"
            link={gist.comments_url}
            files={gist.files}
          />
          <Links
            linkType={"star"}
            linkName="star"
            link={gist.owner.starred_url}
            files={gist.files}
          />
        </div>
      </div>
      <DateComponent gist={gist} />
      <div style={{ marginTop: 10, marginBottom: 10 }}>
        Generated by XState Viz: https://xstate.js.org/viz
      </div>
      <div>
        {Object.keys(gist.files).map((fileName) => {
          return (
            <div style={{ display: "inline-block" }}>
              <img alt="Avatar" width={30} style={{ borderRadius: "50%" }} />
              <span style={{ marginLeft: 5, marginRight: 5, fontSize: 12 }}>
                <a
                  href={gist.files[fileName].raw_url}
                  target="_blank"
                  rel="noreferrer"
                >
                  {fileName}
                </a>
              </span>
            </div>
          );
        })}
      </div>
      <hr style={{ marginTop: 50 }} />
    </GistWrapper>
  );
};

const GistWrapper = styled.div`
  margin: auto;
  width: 50%;
  padding: 10px;
`;

export default Gist;
